name: inime2
version: 1.0.0+1
publish_to: none
description: A project get anime trending and info anime.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts : 
    - family: Imposible Fill
      fonts:
        - asset: fonts/Imposible_fill.ttf

